/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cube_Bricks({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Cube_Bricks.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube042.geometry} material={materials.Red} />
      <mesh geometry={nodes.Cube042_1.geometry} material={materials.Red_Dark} />
    </group>
  )
}

useGLTF.preload('/models/Cube_Bricks.gltf')
