/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cube_Question({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Cube_Question.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube249.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Cube249_1.geometry} material={materials.Blue_Dark} />
      <mesh geometry={nodes.Cube249_2.geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('/models/Cube_Question.gltf')
