/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cube_Exclamation({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Cube_Exclamation.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube253.geometry} material={materials.BrightGreen} />
      <mesh geometry={nodes.Cube253_1.geometry} material={materials.BrightGreen2} />
      <mesh geometry={nodes.Cube253_2.geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('/models/Cube_Exclamation.gltf')
