/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Enemy({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Enemy.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MonsterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <group name="Enemy_Body">
            <skinnedMesh name="Cube000" geometry={nodes.Cube000.geometry} material={materials.Main} skeleton={nodes.Cube000.skeleton} />
            <skinnedMesh name="Cube000_1" geometry={nodes.Cube000_1.geometry} material={materials.Main_Dark} skeleton={nodes.Cube000_1.skeleton} />
          </group>
          <skinnedMesh name="Enemy_Eyes" geometry={nodes.Enemy_Eyes.geometry} material={materials.Eyes} skeleton={nodes.Enemy_Eyes.skeleton} />
          <group name="Enemy_Face">
            <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Main_Dark} skeleton={nodes.Cube001.skeleton} />
            <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Horns} skeleton={nodes.Cube001_1.skeleton} />
            <skinnedMesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.Tongue} skeleton={nodes.Cube001_2.skeleton} />
            <skinnedMesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials.Teeth} skeleton={nodes.Cube001_3.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Enemy.gltf')
