/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Heart_Outline({ x, y, z, chat, onClick, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/Heart_Outline.gltf");
  return (
    <>
      {chat?.isUsed ? null : (
        <group
          ref={group}
          {...props}
          dispose={null}
          onClick={() => onClick(chat.answerID, chat.content)}
        >
          <mesh
            geometry={nodes.Heart_Outline.geometry}
            material={materials.Red}
            position={[x, y, z]}
          />
        </group>
      )}
    </>
  );
}

useGLTF.preload("/models/Heart_Outline.gltf");
