/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SmallBarn({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/SmallBarn.gltf");
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[0, -1.5, 0]}
      scale={1}
    >
      <group rotation={[-Math.PI / 2, -0.02, 1.45]} scale={1.35}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials.LightRed}
        />
        <mesh
          geometry={nodes.Cube013_3.geometry}
          material={materials.RoofBlack}
        />
      </group>
      <group
        position={[-39.79, 104.88, 266.57]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh geometry={nodes.Cube008.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Cube008_2.geometry}
          material={materials.LightRed}
        />
      </group>
      <group
        position={[52.93, 309.63, 283.9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={75.5}
      >
        <mesh geometry={nodes.Cube023.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={materials.LightRed}
        />
      </group>
      <group
        position={[-51.8, 309.63, 284.69]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={75.5}
      >
        <mesh geometry={nodes.Cube022.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Cube022_1.geometry}
          material={materials.LightRed}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/SmallBarn.gltf");
