/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bridge_Small({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/Bridge_Small.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Bridge_Small.geometry} material={materials.Wood} />
    </group>
  );
}

useGLTF.preload("models/Bridge_Small.gltf");
