/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cloud_1({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Cloud_1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cloud_1.geometry} material={materials.Cloud} />
    </group>
  )
}

useGLTF.preload('/models/Cloud_1.gltf')
