/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Grass_3({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/Grass_3.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Grass_3.geometry} material={materials.Green_Light} />
    </group>
  )
}

useGLTF.preload('models/Grass_3.gltf')
