/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Grass_2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Grass_2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Grass_2.geometry} material={materials.Green_Light} />
    </group>
  )
}

useGLTF.preload('/models/Grass_2.gltf')
