/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Coin({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Coin.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Cylinder012_1.geometry} material={materials.Gold_Dark} />
    </group>
  )
}

useGLTF.preload('/models/Coin.gltf')
