/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Star({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Star.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Star.geometry} material={materials.Gold} />
    </group>
  )
}

useGLTF.preload('/models/Star.gltf')
